/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import com.azure.storage.blob.*;
import com.azure.storage.blob.models.*;

public class App {

    // Add your sas key here
    static String sasUrl = "https://FULL SAS URL HERE";

    public static void main(String[] args) {
        BlobClient blobClient = new BlobClientBuilder().endpoint(sasUrl).blobName("NAME OF THE BLOB HERE (if not in SAS url)").buildClient();
        System.out.println(blobClient.getProperties().getMetadata());
    }
}
